production:
 adapter: postgresql
 encoding: unicode
 database: whitepeoplemeet_app_production
 pool: 5
 user: postgres
 password: root
 host: localhost

development:
 adapter: postgresql
 encoding: unicode
 database: whitepeoplemeet_development
 pool: 5
 user: postgres
 host: localhost
 password: 12345678
 Port: 5432




