# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa71f34578f530f87c505fb6ae0cbd12a5641bdaa42f4e1b3161d9d7983f091342aef09fea77559a475d057319b39f030897c02236d5f88d04ed0fe0d3b5ab74

test:
  secret_key_base: a34294c6e8f164fead30d3e167b06bffa182707f494869d139235172691c4719861d729f2a15200b76fea1cbe1c65573526db738accf9de0458f24a9577c37a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
